# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://dthiagarajan.github.io/breakhis_gradcam/"

git_url = "https://github.com/dthiagarajan/breakhis_gradcam/tree/master/"

def custom_doc_links(name): return None
