# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"model_urls": "00_resnet.ipynb",
         "conv3x3": "00_resnet.ipynb",
         "conv1x1": "00_resnet.ipynb",
         "BasicBlock": "00_resnet.ipynb",
         "Bottleneck": "00_resnet.ipynb",
         "ResNet": "00_resnet.ipynb",
         "resnet18": "00_resnet.ipynb",
         "resnet34": "00_resnet.ipynb",
         "resnet50": "00_resnet.ipynb",
         "resnet101": "00_resnet.ipynb",
         "resnet152": "00_resnet.ipynb",
         "BreaKHisDataset": "01_data.ipynb",
         "initialize_datasets": "01_data.ipynb",
         "log": "02_utils.ipynb",
         "mixup_data": "02_utils.ipynb",
         "setup_logging_streams": "02_utils.ipynb",
         "train": "02_utils.ipynb",
         "validate": "02_utils.ipynb",
         "get_param_lr_maps": "02_utils.ipynb",
         "setup_optimizer_and_scheduler": "02_utils.ipynb",
         "checkpoint_state": "02_utils.ipynb",
         "show_image": "03_vis.ipynb",
         "get_preprocessed_image": "03_vis.ipynb",
         "show_heatmap_and_original": "03_vis.ipynb"}

modules = ["resnet.py",
           "data.py",
           "utils.py",
           "vis.py"]

doc_url = "https://dthiagarajan.github.io/breakhis_gradcam/"

git_url = "https://github.com/dthiagarajan/breakhis_gradcam/tree/master/"


def custom_doc_links(name): return None
